In [1]:
import torch

In [2]:
x = torch.tensor(2.,requires_grad =True)

In [3]:
f_x = 2*x**4 + x**3 + 3*x**2 +5*x + 1

2*2**4 + 2**3 + 3*2**2 +5*2 + 1

63

In [4]:
f_x

tensor(63., grad_fn=<AddBackward0>)

In [5]:
type(f_x)

torch.Tensor

In [6]:
f_x.backward()

In [7]:
f_x

tensor(63., grad_fn=<AddBackward0>)

In [8]:
x.grad

tensor(93.)

In [9]:
f_dervi = 8*2**3 + 3*2**2 +6*2+5

In [10]:
f_dervi

93

## Multi

In [30]:
x = torch.tensor([[1.,2.,3.], [3.,2.,1.]], requires_grad = True)

In [31]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [32]:
y = 3*x +2 #x is derivative

In [33]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [34]:
z = 2*y**2 

In [35]:
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [36]:
out = z.mean()

In [37]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


### find the gradient of x wrt to out

In [38]:
out.backward()

In [39]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])