In [3]:
import numpy as np
import torch 

In [26]:
arr = np.arange(1,12)
print(arr)
print(f'{arr.dtype} data type')

[ 1  2  3  4  5  6  7  8  9 10 11]
int32 data type


### torch.from_numpy()

In [27]:
arr_torch = torch.from_numpy(arr)

In [28]:
arr_torch

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)

In [29]:
arr[0]=99
arr_torch

tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)

In [30]:
arr_torch.dtype

torch.int32

### torch.tensor()

In [31]:
arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
arr_torch = torch.tensor(arr)
print(arr_torch)

tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)


In [33]:
arr[0] =978

In [34]:
arr_torch

tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)

### torch.Tensor() 

T-  returns floats <br>
t-  retains data type <br>

same as torch.FloatTensor()

In [41]:
arr

array([978,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [38]:
arr_tor = torch.Tensor(arr)

In [39]:
arr_tor.dtype

torch.float32

In [40]:
arr_torch.dtype

torch.int32

In [42]:
arr_tor_float = torch.FloatTensor(arr)

In [43]:
arr_tor_float = arr_tor

## torch.empty()

In [44]:
torch.empty(2,4)

tensor([[0.0000e+00, 6.6141e-43, 1.8754e+28, 4.1586e-05],
        [4.1766e-08, 1.2802e-11, 1.3002e+22, 2.6703e-06]])

## torch.zeros

In [107]:
zeros = torch.zeros(4,3,dtype=torch.int64)
print(zeros)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## torch.ones

In [100]:
ones = torch.ones(2,3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


## torch.arange

In [105]:
arange = torch.arange(0,20,1).reshape(4,-1)
print(arange)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


## torch.linspace

In [65]:
torch.linspace(0,20,12).reshape(3,4)

tensor([[ 0.0000,  1.8182,  3.6364,  5.4545],
        [ 7.2727,  9.0909, 10.9091, 12.7273],
        [14.5455, 16.3636, 18.1818, 20.0000]])

# changing dtype

In [66]:
arr_tor

tensor([978.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.])

In [67]:
arr_tor.dtype

torch.float32

In [69]:
arr_tor.type(torch.int32)

tensor([978,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       dtype=torch.int32)

## torch.rand

In [70]:
torch.rand(4,3)

tensor([[0.0336, 0.4166, 0.7169],
        [0.4240, 0.3917, 0.2753],
        [0.5309, 0.9136, 0.1907],
        [0.3885, 0.3272, 0.3036]])

## torch.randn

In [89]:
randn = torch.randn(4,3)
print(randn)

tensor([[ 1.1321,  0.0461,  1.7751],
        [ 0.7689, -0.5659, -0.2497],
        [-0.0225,  2.5757,  0.3928],
        [ 0.5975,  0.6806, -1.0219]])


## torch.randint

In [83]:
randint = torch.randint(0,10,(5,5))
print(randint)

tensor([[8, 5, 1, 7, 8],
        [4, 3, 4, 4, 5],
        [7, 1, 3, 1, 1],
        [8, 7, 2, 8, 6],
        [1, 2, 2, 8, 3]])


# \_like modules

randn_like(some_data_object)  
randint_like(some_data_object)  
rand_like(some_data_object)  

In [96]:
torch.rand_like(randn)

tensor([[0.1299, 0.9693, 0.2214],
        [0.5110, 0.9174, 0.9605],
        [0.8656, 0.4704, 0.8977],
        [0.1647, 0.8156, 0.5999]])

In [101]:
torch.randn_like(ones)

tensor([[0.3088, 1.7550, 1.1587],
        [1.4731, 0.5654, 1.7880]])

In [120]:
torch.randint_like(zeros,10,20)
#only in this case pass low and high

tensor([[12, 15, 19],
        [11, 12, 17],
        [18, 18, 12],
        [19, 12, 14]])

### torch.maual_seed()

In [121]:
torch.manual_seed(12)
torch.randint_like(zeros,10,20)
#only in this case pass low and high

tensor([[13, 13, 12],
        [17, 13, 16],
        [19, 13, 18],
        [10, 14, 13]])

In [122]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])