In [1]:
import torch as t
import numpy as np

In [2]:
X = t.arange(6).reshape(3,2)

In [4]:
X

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [5]:
X[1,1]

tensor(3)

In [13]:
dat = X[:,1]
print(dat)
print(dat.shape)

tensor([1, 3, 5])
torch.Size([3])


In [16]:
dat = X[:,1:]
print(dat)
print(dat.shape)

tensor([[1],
        [3],
        [5]])
torch.Size([3, 1])


# view & reshape

In [35]:
arr = t.arange(1,21)

In [36]:
reshape_ = arr.reshape(4,5)
print(reshape_)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


In [37]:
arr

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [38]:
view_ = arr.view(4,5)
print(view_)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


In [39]:
arr

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [40]:
arr[0] =999

In [41]:
view_

tensor([[999,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]])

In [42]:
reshape_

tensor([[999,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]])

In [88]:
array = [[1,2,3,4,5],[6,7,8,9,10]]


In [89]:
non_Contiguous_tensor = t.Tensor(array).transpose(0,1)

In [90]:
non_Contiguous_tensor.is_contiguous()

False

In [91]:
non_Contiguous_tensor.view(-1,5)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [92]:
non_Contiguous_tensor.contiguous().view(-1,5)

tensor([[ 1.,  6.,  2.,  7.,  3.],
        [ 8.,  4.,  9.,  5., 10.]])

# Basic Operations

In [105]:
a = t.tensor([1., 2 , 3])
a.dtype

torch.float32

In [106]:
b = a*2

In [107]:
b

tensor([2., 4., 6.])

In [108]:
a+b

tensor([3., 6., 9.])

In [109]:
t.add(a,b)

tensor([3., 6., 9.])

### Inplace _

In [110]:
a

tensor([1., 2., 3.])

In [111]:
b

tensor([2., 4., 6.])

In [112]:
a.mul_(b)

tensor([ 2.,  8., 18.])

In [113]:
a

tensor([ 2.,  8., 18.])

## dot product

In [115]:
a.dot(b)

tensor(144.)

## Multiply

In [118]:
mat1 = t.randint(1,5,(3,2))
print(mat1)

tensor([[3, 4],
        [2, 3],
        [1, 1]])


In [119]:
mat2 = t.randint(1,5,(2,3))
print(mat2)

tensor([[2, 4, 2],
        [1, 2, 1]])


In [120]:
t.mm(mat1,mat2)

tensor([[10, 20, 10],
        [ 7, 14,  7],
        [ 3,  6,  3]])

In [121]:
mat1@mat2

tensor([[10, 20, 10],
        [ 7, 14,  7],
        [ 3,  6,  3]])

# Euclidean norm

In [132]:
vec = mat1[:,0].type(t.float32)

In [134]:
vec

tensor([3., 2., 1.])

In [133]:
vec.norm()

tensor(3.7417)

In [135]:
vec.numel()

3